# A string used to distinguish different Supabase projects on the same host. Defaults to the working directory name when running `supabase init`.
project_id = "qongjclaipcgmbcoyfmt"

[api]
port = 54321

[db]
port = 54322

[studio]
port = 54323
